#!/bin/sh
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
Color_Off='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

if [ $USER != root ]
	then echo "$Red[x]You Don't have root user privileges"
	exit
else
	clear
	echo """$Yellow
  _____              _          _  _  _                     
 |_   _|            | |        | || |(_)                    
   | |   _ __   ___ | |_  __ _ | || | _  _ __    __ _       
   | |  |  _ \ / __|| __|/ _  || || || ||  _ \  / _  |      
  _| |_ | | | |\__ \| |_| (_| || || || || | | || (_| | _  _ 
 |_____||_| |_||___/ \__|\__,_||_||_||_||_| |_| \__, |(_)(_)
                                                 __/ |      
                                                |___/      
		$Red<$Color_Off Tool Information $Red>$Color_Off
	
	[$Cyan 1 $Color_Off]$Blue Tool Name $Red:$Color_Off The watcher
	[$Cyan 2 $Color_Off]$Blue Version   $Red:$Color_Off 5.0
	[$Cyan 3 $Color_Off]$Blue Coded By  $Red:$Color_Off DevoOverkill9
	[$Cyan 4 $Color_Off]$Blue Tool Type $Red:$Color_Off Sniffing and Spoofing


	"""
	echo "[$Blue*$Color_Off]We gonne install some tools to your system\n"
	read -p "Continue? (y,n): " yn
	
	case $yn in
		[Yy]* )
			echo "[$BBlue*$Color_Off]Updating your system"
			apt-get -qq update
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install python-pip
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			echo "[$BBlue*$Color_Off]Installing iptables.."
			apt-get -qq install iptables
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi

			echo "[$BBlue*$Color_Off]Installing Sniffing Tools.."
			apt-get -qq install driftnet
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install sslstrip
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install netdiscover
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install bettercap
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install hping3
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			apt-get -qq install apache2
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools"
			fi
			
			echo "[$BBlue*$Color_Off]Installing bridge utils"
			apt-get -qq install bridge-utils
			if [ $? != 0 ]
				then echo "[$Redx$Color_Off]Error while installing requierd tools!"
			fi
			
			echo "[$Blue*$Color_Off]Installing Apache Server"
			echo "[$BBlue*$Color_Off]Installing the tool.."
			chmod 777 thewatcher
			rm /usr/bin/thewatcher
			cp thewatcher /usr/bin/
			echo "[$Green+$Color_Off]Tool has been installed successfully!\n"
			echo "$Red To run the tool just type in your terminal :$Color_Off sudo thewatcher";;
		[Nn]* ) echo "Exiting..";;
		
		* ) echo "y = yes , n = no";;
	esac
	
fi